### ISSUE TITLE
1.1 Net transfers to developing countries

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/net_flows#6]
A chart focused on showing the trend of **net flows** to developing countries in the last two decades.

[This chart](https://observablehq.com/@one-campaign/net-flows#cell-354) is an attempt to visualise this data, designed to explore what's happened in different countries/regions.

The objective of this chart is to show what's happened, rather than allow for exploration. Hence we should think about annotations, or even scrollytelling, if it helps to make the point eloquently. If we can enable exploration, that's a nice, secondary goal.

This chart will appear towards the beginning of the piece, in a section that looks at trends. It is trying to make the point that 
> Net transfers to developing countries have been in decline over the past few years, and are at the lowest level for the past 2 decades. Lower middle and middle income countries with market access hit hardest, as private debt service payments have soared.

**Comment by lpicci96** [comment]
Preliminary idea. Using multiples rather than $ values to show what has happened. We can probably include a filter to select income levels and countries. I would prefer showing a single line rather than multiple because values can fluctuate a significant amount.
@jm-rivera @Mattie-P 

<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/c42bfa89-4088-480c-9ab2-4af69a89d981">

**Comment by jm-rivera** [comment]
Thank you Luca. Overall:
- It's a clearer picture with just the net flows. However, I'm not sure the multiples are adding that much value, when the line would be the same shape just showing the dollar amount, and it would allow people to 'see' the actual amount straightaway.
- The annotation is helpful to indicator more inflows. I wonder if there should be another one at the peak saying "In 2012, inflows exceeded outflows by $xx billion", and another annotation at 2022 saying "In 2022, inflows were almost equal to outflows".

On wording:
- this is not 'just' development finance, as it is also non-concessional lending.
- unless very loosely defined, this is not a group of EMDEs. I'd just call it developing countries since a) it's not an acronym, and b) we're looking at LICs and MICs (with data).

@Mattie-P what do you think?

Also @sharcourt14 in case you want to weight in on multiples vs. money or generally on the chart

**Comment by Mattie-P** [comment]
Hi both. Overall:
- I am not a huge fan of the multiples scale. I think for the first, top line figure, the reader just wants to know the scale of the issue i.e. net transfers were once hundreds of billions, and now they are near 0 globally. This way, we are giving the reader monetary values they can use for headline stats, or comparison to the aid figures they have in their head, etc. 
- I agree with the need for simplicity to drill home quite a complex point. I think the use of just net transfers does this well. I do wonder whether we could include options to add in inflows and outflows (at the fully aggregated level) for the user to interact with if they want to understand how this has changed? They could be formatted as a fairly transparent red (outflows) and blue (inflows) to not add too much to the visual of the graph, but understand this is still unneccessary complexity. 

For discussion, given that are arguement is for increased concessional funding and grants, I worry that this graph is maybe missing the point of the problem? That funding is more for LICs and LMICs, so the context of net transfers is important:  Private borrowing (especially private bonds) has increased substantially over 2010 - 2021. 'Private - bonds' alone go from 22% of **inflows** in 2009 to an average of 44% over 2017-2021. There is a significant decrease in 2022 (from $236b to $94b **inflows**), which drives a lot of net flows drop, but China fell from $90b of private bond inflows in 2021 to $24b in 2022. For Russia, who has no inflows data in 2022 (due to Ukraine), this drop is from $12bn to $0bn.  Over this same period, China increased its outflows due to private bonds from $36b to $60b, and Russia also paid back an additional $7b in 2022. So I wonder if the message of this first graph is hiding the story? It looks like there is a discussion on Slack on how to proceed, but I think we should have these details in mind when building any aggregate data graphs. Would be great to hear your thoughts to see if I am well off the mark here/missing the point of the paper.

**Comment by lpicci96** [comment]
This is another option. Potentially we could include both- start with the overall and breakdown by type in this faceted chart. But The text would need to integrate the charts @sharcourt14 

Please ignore styling etc it will be fixed.
@jm-rivera @Mattie-P 

<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/6c9f175f-280c-41c7-bf3e-9c8364ee53fb">

**Comment by sharcourt14** [comment]
Sorry I have no idea how to properly comment on this. I think this is good, but again I think it's necessary to have a separate line graph then for China (and then exclude China from the other bilateral or privte flows) because China and private flows are the key drivers here so we need to highlight them both in all charts I think


Sara Harcourt | +44 7765 241737

**Comment by jm-rivera** [comment]
Maybe we break it down as "Bilateral (excl. China)" "Multilateral" "Private (excl. China)" "China (bilateral + private)"?

**Comment by lpicci96** [comment]
Like this?

<img width="793" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/50482f34-d3f5-4374-8c6e-b9f97c174a51">

**Comment by sharcourt14** [comment]
Yes, this is great thanks! I presume instead of world it will say all EMDEs or something? and then we can break down by income group or region? That would be helpful

**Comment by sharcourt14** [comment]
Actually @lpicci96 and @jm-rivera just realising this is showing net transfers, when actually in the text I'm going to be talking about inflows decreasing, so I think it would be clearer to just show the inflows themselves, rather than net. And finally could we not just have all the lines on one graph in different colors since there are only 4 of them?

**Comment by lpicci96** [comment]
This will be the final chart for 1.1

https://public.flourish.studio/visualisation/17517277/

<img width="792" alt="image" src="https://github.com/ONEcampaign/net_flows/assets/56567716/7a55f021-9800-4788-a26b-e2151089f5bc">

**Comment by jm-rivera** [comment]
Closing since we have a final version of the chart (connected to the data)
